apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-jcsx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-jcsx
    app.kubernetes.io/part-of: test-app-lqwr
  name: test-component-jcsx
  namespace: build-e2e-hacbs-cyfq
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component-jcsx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component-jcsx
    spec:
      containers:
      - image: quay.io/psturc/test-images:51fa985510c5448b902b30e17915f309
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources: {}
status: {}
